### ISSUE TITLE
Page warns that 5.1 will soon be end of life and suggests using 5.0 SP3 instead?!

### ISSUE THREAD

**Issue by DanGough** [MicrosoftDocs/mdop-docs#17]
Surely downgrading is not the correct advice here?

[https://github.com/MicrosoftDocs/mdop-docs/blob/public/mdop/appv-v5/index.md](https://github.com/MicrosoftDocs/mdop-docs/blob/public/mdop/appv-v5/index.md)

**Comment by exchange12rocks** [comment]
Seems the date is incorrect: the new one is in 2026

https://learn.microsoft.com/en-us/lifecycle/announcements/mdop-extended

**Comment by aczechowski** [comment]
I'll cleanup that article shortly. Thanks @DanGough 
This issue will auto-close when the pull request merges
