### ISSUE TITLE
Since MBAM&Configuration manager integration no more supported page should be removed or archived. 

### ISSUE THREAD

**Issue by nascar3000** [MicrosoftDocs/mdop-docs#21]
https://learn.microsoft.com/en-us/microsoft-desktop-optimization-pack/mbam-v25/mbam-25-supported-configurations
Important

Since all versions of Configuration Manager that MBAM supported are out of support, use of MBAM with Configuration Manager is no longer supported. Customers using MBAM with Configuration Manager should [migrate to Configuration Manager BitLocker Management](https://learn.microsoft.com/en-us/mem/configmgr/protect/deploy-use/bitlocker/migration-considerations).

**Comment by aczechowski** [comment]
Thanks @nascar3000 for the feedback. I'm working on retiring much of the MDOP content.
